### ISSUE TITLE
Hyperparameter on Resnet50 - wrn16x2

### ISSUE THREAD

**Issue by flymin** [megvii-research/mdistiller#6]
Hi, in table 12 of your paper, the ACC from ResNet50 - wrn16x2 with DKD is 76.60. However, I use the Resnet50 ckpt provided in this repo and hyperparameters as follows:
```
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
```
The best ACC I got is only 75.52. Could you please share your config?
